### ISSUE TITLE
Setup Deployment

### ISSUE THREAD

**Issue by borislavkb** [borislavkb/bake-app#1]
## Value statement

As a developer and contributor to this project I want to see every increment deployed so its easy to test.

## Description

App is continuously deployed so it is easy to test and release new versions. 

## Acceptance Criteria

- [x] ```main```branch should be deployed after every change. 
- [x] Every PR should have a corresponding deployment so it's easy for reviewers to check.

## Tasks

- [x] Setup Heroku deployment - for test purposes. 

- [x] Connect Heroku to current repo 

- [x] Double-check if configured properly. 

## Complexity

Small

**Comment by borislavkb** [comment]
Deploy app to Heroku successful. 
Auto-deployment feature enabled.
