### ISSUE TITLE
Setup basic  HTML layout

### ISSUE THREAD

**Issue by borislavkb** [borislavkb/bake-app#2]
## Value statement 

As a start of the project I would like to have a basic HTML structure in accordance with initial design idea. 

## Description 

Add HTML basic structure

## Acceptance criteria

- [x] HTML structure
- [x] PR to be reviewed

## Tasks
- [x] install React-router-dom
- [x] Add header, main and footer.
- [x] Add background-image
- [x] Add Nav items
- [x] Add Icons as Nav items
- [x] define Routes for ListProducts and Home
- [x] Create components
- [x] Add Style
